-- CREAREMOS UNA TABLA MUY SIMPLE PARA PROBAR EL PODER DE SQL 

CREATE TABLE DANCE(ID_DANCE INTEGER, NOMBRE VARCHAR2(40), EDAD INTEGER); 
-- PRENDEMOS EL SERVIDOR EN MODO DESARROLADOR 
SET SERVEROUTPUT ON;
-- VAMOS A EMPEZAR CON UN BLOQUE PL SQL 
--Crear un bloque pl sql que genere 200000 registro en secuencia ascendente en la tabla dance 
BEGIN 

   FOR I IN 1..200000 LOOP
     INSERT INTO DANCE VALUES (I,'MARCOS',22);
    
     END LOOP;
   END;
   /
-- HACEMOS UN SELECT PARA VER QUE HIZO

SELECT * FROM DANCE;

--SISTEMITA DE PELICULAS LA DE SALAS SERA DE TAREA

-- DAR SOLO UNA VES CLIC 
CREATE TABLE PELICULA (ID_PELICULA INTEGER, 
                      TITULO VARCHAR2(120),
                      SINOPSIS VARCHAR2(500),
                      CLASIFICACION VARCHAR2(5), 
                      CONSTRAINT PK_ID_PELICULA PRIMARY KEY( ID_PELICULA )
                      );
                      
 -- DESCRIBE= PARA VER LA ESTRUCTURA DE LA TABLA                      
                      DESCRIBE PELICULA;
                      
CREATE TABLE HORARIOS (ID_HORARIO INTEGER,
                       ID_PELICULA INTEGER,
                       HORARIO VARCHAR2(8),
                       CONSTRAINT PK_ID_HORARIO PRIMARY KEY(ID_HORARIO),
                       CONSTRAINT FK1_ID_PELICULA FOREIGN KEY(ID_PELICULA) REFERENCES PELICULA (ID_PELICULA)
                       );
                       
                       DESCRIBE HORARIOS;
                       
                       
CREATE TABLE SALAS (ID_SALA INTEGER,
                    ID_PELICULA INTEGER,
                    NUM_SALA VARCHAR2(8),
                    CONSTRAINT PK_ID_SALA PRIMARY KEY(ID_SALA),
                       CONSTRAINT FK2_ID_PELICULA FOREIGN KEY(ID_PELICULA) REFERENCES PELICULA (ID_PELICULA)
                       );
                    
                       DESCRIBE SALAS;
                       
                      

DECLARE
-- AQUI SE DECLARA LAS VARIABLES USARSE
EDAD INTEGER;
YEARS INTEGER;
BEGIN
-- AQUI VA LA LOGICA DE TU PROGRAMITA

YEARS:=22;
EDAD:=YEARS*365;

DBMS_OUTPUT.PUT_LINE('TU EDAD EN DIAS: '||EDAD);

END;
/

