-- CREAREMOS UNA TABLA MUY SIMPLE PARA PROBAR EL PODER DE SQL 

CREATE TABLE DANCE(ID_DANCE INTEGER, NOMBRE VARCHAR2(40), EDAD INTEGER); 
-- PRENDEMOS EL SERVIDOR EN MODO DESARROLADOR 
SET SERVEROUTPUT ON;
-- VAMOS A EMPEZAR CON UN BLOQUE PL SQL 
DECLARE
-- AQUI SE DECLARA LAS VARIABLES USARSE
EDAD INTEGER;
YEARS INTEGER;
BEGIN
-- AQUI VA LA LOGICA DE TU PROGRAMITA

YEARS:=22;
EDAD:=YEARS*365;

DBMS_OUTPUT.PUT_LINE('TU EDAD EN DIAS: '||EDAD);

END;
/
